
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int READ = 7;
  public static final int NOTEQ = 25;
  public static final int PLUS = 10;
  public static final int OR = 19;
  public static final int INT = 3;
  public static final int SEMI = 15;
  public static final int LEFTPAR = 12;
  public static final int END = 6;
  public static final int GREATER = 26;
  public static final int RIGHTPAR = 13;
  public static final int ID = 17;
  public static final int WRITE = 8;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 5;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int DIV = 28;
  public static final int GREATEREQ = 27;
  public static final int MINUS = 14;
  public static final int CONST = 21;
  public static final int error = 1;
  public static final int ASSIGN = 29;
  public static final int EQ = 24;
  public static final int LESSEQ = 23;
  public static final int BOOL = 4;
  public static final int FOR = 18;
  public static final int REAL = 9;
  public static final int MUL = 11;
  public static final int LESS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "INT",
  "BOOL",
  "BEGIN",
  "END",
  "READ",
  "WRITE",
  "REAL",
  "PLUS",
  "MUL",
  "LEFTPAR",
  "RIGHTPAR",
  "MINUS",
  "SEMI",
  "COMMA",
  "ID",
  "FOR",
  "OR",
  "AND",
  "CONST",
  "LESS",
  "LESSEQ",
  "EQ",
  "NOTEQ",
  "GREATER",
  "GREATEREQ",
  "DIV",
  "ASSIGN"
  };
}

